### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by FreshlyBrewedCode** [nghiaho12/rigid_transform_3D#1]
Hi, I stumbled across this code and it turns the ```rigid_transform_3D``` python implementation is exactly what I needed for a project I am working on. I noticed that there is no license included with this repo. Would you mind adding a license to clarify how the code can be used?

**Comment by jewettaij** [comment]
It's been almost a month since this issue was raised.
...So here are several github repositories using the MIT license which (I think) do the same thing:

#### in python
https://github.com/jewettaij/superpose3d

#### in C++
https://github.com/jewettaij/superpose3d_cpp

*(Disclaimer: I wrote them.  I hope it is not horribly obnoxious to post this here.)*

License details are crucial.  Without it, code is unusable.  (Except, perhaps in an inspirational sense.  I just spent 2 weeks dealing with licenses and rewriting existing code.)

**Comment by lrq3000** [comment]
@nghiaho12 please add a license to clarify usage, your tutorial is really great and it would be awesome if your code could be reused in other libraries!

**Comment by nghiaho12** [comment]
Done!
